---
title: "GAMEX seminar series"
description: "Likun Zhang (University of Missouri)"
meeting-date: "2026-05-15"
categories: [GAMEX]
format:
  html:
    page-layout: full
---

**Description:** This online seminar is organized within the [GAMEX project](https://gamex-network.github.io/) with the support of the Glasgow–Edinburgh Extremes Network ([GLE²N](https://glen-scotland.github.io/glen/)) and CIRCE.

**Date:** 15 May 2026

**Time:** 9:00 CT (14:00 UTC / 15:00 BST / 16:00 CEST)

**Speaker:** Likun Zhang (University of Missouri)    

**Title:**  
*Modeling Spatio-temporal Extremes via Conditional Variational Autoencoders*

**Abstract:**  
Extreme weather events are widely studied in fields such as agriculture, ecology, and meteorology. The spatio-temporal co-occurrence of extreme events can strengthen or weaken under changing climate conditions. In this paper, we propose a novel approach to model spatio-temporal extremes by integrating climate indices via a conditional variational autoencoder (cXVAE). A convolutional neural network (CNN) is embedded in the decoder to convolve climatological indices with the spatial dependence within the latent space, thereby allowing the decoder to depend on the climate variables. There are three main contributions. First, through extensive simulations, we show that the proposed conditional XVAE accurately emulates spatial fields and recovers spatially and temporally varying extremal dependence with very low computational cost after training. Second, we provide a simple and scalable approach to detecting condition-driven shifts and assessing whether the dependence structure is invariant to the conditioning variable. Third, when dependence is condition-sensitive, the conditional XVAE supports counterfactual experiments by intervening on the climate covariate and propagating the change through the learned decoder to quantify differences in joint tail risk, co-occurrence ranges, and return metrics.We illustrate the methodology by analyzing the monthly maximum Fire Weather Index (FWI) over eastern Australia (2014–2024), conditioned on the El Nino/Southern Oscillation (ENSO) index.

**Access link:** 
[Join the seminar on Zoom](https://uofglasgow.zoom.us/j/87240389315?pwd=WPO6tY8MKSwFojlUn6iUHTbEXx58DY.1)
